@startuml
'https://plantuml.com/sequence-diagram

autonumber

Solider.CombatEntity -> Solider.SpellComponent施法组件 : SpellWithPoint(开始释放一个技能)
Solider.SpellComponent施法组件 --> Solider.CombatEntity : 获取一个SpellAction施法行为
Solider.CombatEntity -> Solider.SpellComponent施法组件: 返回一个SpellAction
Solider.SpellComponent施法组件 -> Solider.CombatEntiry.SpellAction : SpellSkill施法
Solider.CombatEntiry.SpellAction->Solider.CombatEntiry.SpellAction : PreProcess前置处理
Solider.CombatEntiry.SpellAction --> Solider.CombatEntity : 增加一个 AbilityExecution Entity
Solider.CombatEntity  -> Solider.CombatEntiry.SpellAction : 返回 AbilityExecution技能执行体
Solider.CombatEntiry.SpellAction -> Solider.CombatEntity.Child.AbilityExecution : LoadExecutionEffects
Solider.CombatEntiry.SpellAction -> Solider.CombatEntity.Child.AbilityExecution : BeginExecute
Solider.CombatEntity.Child.AbilityExecution --> Solider.CombatEntity : 设置SpellingExecution = AbilityExecution
Solider.CombatEntity.Child.AbilityExecution -> Solider.CombatEntity.Child.AbilityExecution.ExecutionClipComponent : BeginExecute执行各自的计时器，当条件满足卡开始执行具体技能行为
Solider.CombatEntity.Child.AbilityExecution -> Solider.CombatEntity.Child.AbilityExecution.ExecutionObject.ExecuteClip: BeginExecute
Solider.CombatEntity.Child.AbilityExecution.ExecutionObject.ExecuteClip -> ExecuteClip.ExecuteTimeTriggerComponent.GameTimer: UpdateAsFinish
ExecuteClip.ExecuteTimeTriggerComponent.GameTimer --> Solider.CombatEntity.Child.AbilityExecution.ExecutionObject.ExecuteClip : TriggerEffect
Solider.CombatEntity.Child.AbilityExecution.ExecutionObject.ExecuteClip-> ExecutionAnimationComponent : PlayAnimation
Solider.CombatEntity.Child.AbilityExecution.ExecutionObject.ExecuteClip-> ExecutionCollisionItemComponent : SpawnCollisionItem
ExecutionCollisionItemComponent -> AblityItem : CreateAbilityItemProxyObj：创建技能碰撞体
AblityItem -> OnTriggerEnterCallBack: 设置碰撞检测回调事件
OnTriggerEnterCallBack --> AblityItem: 碰撞时执行回调事件
AblityItem -> CollisionAction : ApplyCollision
CollisionAction --> AblityItem:OnTriggerEvent
AblityItem->AbilityTriggerComponent: OnTrigger
AbilityTriggerComponent -> EffectAssignAbility : AssignEffect
EffectAssignAbility -> EffectDamageComponent : OnTriggerApplyEffect
EffectDamageComponent -> DamageActionAbility : ApplyDamage
DamageActionAbility -> HealthPointComponent : ReceiveDamage造成伤害，修改数值
DamageActionAbility -> ActionPointComponent : TriggerActionPoint(PostReceiveDamage)
ActionPointComponent --> Solider.CombatEntity : OnReceiveDamage造成伤害，做出表现






@enduml